#############################
# Michaael Strausz
# Replication files for chapter
# On 2019 HoC election
# Generate figure 9.3
# 6/1/2022 : 6/1/2022
#############################

#install and load necessary libraries-----------------------
library(ggplot2)
library(tidyverse)
library(reshape2)
library (scales)
library(ggrepel)

#prep the HoC2019 data for merging-------------------------------------
HoC2019$prefec.factor.2019levels<-HoC2019$district.factor.english

#create the prefectures subset for the 2019 HoC election----------------
prefs.2019.hoc.2019<-HoC2019 %>%
  group_by(prefec.factor.2019levels)%>%
  summarise( 
    for.lab.2019.c.mean=mean(Q4_8, na.rm=TRUE),
    percent.neutral.2019=mean(neutral.forlab.100, na.rm=TRUE),
    n=n()
  )

#merge my dataframes----------------------------------------------------
prefs.summary<-merge(prefs.2019.pubop.2017, prefs.2019.hoc.2019,
                     by="prefec.factor.2019levels")
prefs.summary<-merge(prefs.summary, jsratio2019,by="prefec.factor.2019levels")
prefs.summary<-merge(prefs.summary, prefpop,by="prefec.factor.2019levels")

#label only a few points
#add a new character vector called plotname
prefs.summary <- prefs.summary %>%
  mutate(plotname = as.character(prefec.factor.2019levels))

#generate an independent vector with the prefectures I want labeled
preflist <- c("Toyama", "Gunma", "Saitama", "Nagano", "Aomori", "Hokkaido", 
              "Shizuoka", "Tottori/Shimane", "Tokyo", "Kanagawa", "Kyoto",
              "Osaka", "Nara", "Ibaraki", "Shiga", "Yamagata",
              "Okinawa", "Ishikawa", "Hiroshima", "Akita", "Ehime", 
              "Tokushima/Kochi")
prefs.summary <- prefs.summary %>%
  mutate(plotname = ifelse(plotname %in% preflist, plotname, ""))

#generate graph 8.3----------------------------
ggplot(prefs.summary, aes(x = percent.neutral.2019, y = for.lab.2019.c.mean)) +
  geom_point(alpha=.3)+
  geom_text_repel(aes(label = plotname), size=3)+
  geom_smooth(method='lm', formula= y~x, color="black")+
  labs(y = "Mean HoC candidate & DM position on\nforeign labor (higher numbers mean oppose)", 
       x = "Percent of HoC candidates & DMs without foreign labor position",
       caption="Figure generated by author with data from Taniguchi 2019")+
  theme(axis.title.y = element_text(size = 10))+
  theme(axis.title.x = element_text(size=10))
ggsave("Figure 8.3.tiff", units="in",width=8, height=4, dpi=300, compression = 'lzw')


#look for correlations---------------------------------------------------
#look for correlation between pop change and candidate opinion
cor.test(formula = ~ for.lab.2019.c.mean + popchange.201810,
         data = prefs.summary)$p.value
#not sig

#look for correlation between pop change and pub opinion
cor.test(formula = ~ for.lab.2017.mean + popchange.201810,
         data = prefs.summary)
#not sig

#look for correlation between candidate opinion and forpop change
cor.test(formula = ~ for.lab.2019.c.mean + forpopchange.201910,
         data = prefs.summary)
#not sig

#look for correlation between forpop change and public opinion
cor.test(formula = ~ for.lab.2017.mean + forpopchange.201910,
         data = prefs.summary)
#not sig

#look for a correlation between pub opinion and forpop percent
cor.test(formula = ~ for.lab.2017.mean + prefforpct2019,
         data = prefs.summary)
#not sig

#look for correlation between candidate opinion and forpop percent
cor.test(formula = ~ for.lab.2019.c.mean + prefforpct2019,
         data = prefs.summary)
#not sig

#look for a correlation between public opinion and cand position
cor.test(formula = ~ for.lab.2017.mean + for.lab.2019.c.mean,
         data = prefs.summary)
#two tailed sig of 0.1555; not sig, but not awful either

#look for a correlation between public opinion and % cand taking a position
cor.test(formula = ~ for.lab.2017.mean + percent.neutral.2019,
         data = prefs.summary)
#not sig

#look for a correlation between position and % cand taking a position
cor.test(formula = ~ for.lab.2019.c.mean + percent.neutral.2019,
         data = prefs.summary)
#sig

#look for correlation with cand position and js ratio
cor.test(formula = ~ jsratio2019 + for.lab.2019.c.mean,
         data = prefs.summary)
#not sig

#look for a correlation between % cand taking a position and js ratio
cor.test(formula = ~ jsratio2019 + percent.neutral.2019,
         data = prefs.summary)
#not sig

