#############################
# Michaael Strausz
# Replication files for chapter
# On 2019 HoC election
# Generate figure 9.2
# 5/24/2022 : 5/24/2022
#############################

#install and load necessary libraries-----------------------
library(tidyverse)

#make the list and vector that I will use for my loop
party.cand.list<-list(party.cand.agg.2021, party.cand.agg.2019,party.cand.agg.2017,
                      party.cand.agg.2016,party.cand.agg.2014, 
                      party.cand.agg.2013, party.cand.agg.2012,
                      party.cand.agg.2010, party.cand.agg.2009)
year.vector<-c(2021,2019,2017,2016, 2014,2013,2012,2010,2009)

#start the dataframe
LDP.multiyear<-
  party.cand.list[[1]][party.cand.list[[1]]$party.factor.english=="LDP",]
year<-year.vector[1]
LDP.multiyear<-cbind(LDP.multiyear,year)

#use a loop to complete the dataframe
for(i in 2:length(year.vector)) {
  j<-party.cand.list[[i]][party.cand.list[[i]]$party.factor.english=="LDP",]
  year<-year.vector[i]
  j<-cbind(j,year)
  LDP.multiyear<-rbind(LDP.multiyear,j)
}

#create a HOC/HOR dataframe
LDP.multiyear$hocor<-c("hor","hoc","hor","hoc","hor","hoc", "hor","hoc","hor")
LDP.multiyear$hocor<-as.factor(LDP.multiyear$hocor)


ggplot(LDP.multiyear, aes(x = as.factor(year), y = forlab.mean, group=hocor, linetype=hocor)) +
  geom_line(size=1.4)+
  geom_text(aes(label = round(forlab.mean, digits=1)), 
            vjust = ifelse(LDP.multiyear$year==2012,.25,
                           ifelse(LDP.multiyear$year==2010,.4,-.25)),
            hjust=ifelse(LDP.multiyear$year==2012,1.5,
                         ifelse(LDP.multiyear$year==2010,1.55,1)), 
            colour="black")+
  labs(x=NULL, 
       y="Percent of LDP Diet candidates & DMs\nsupporting increased foreign labor")+
  scale_linetype_discrete(labels = c("House of Councilors", "House of Representatives"),
                          guide = guide_legend(title = NULL))+
  theme(axis.title.y = element_text(size = 13))+
  theme(axis.text.x = element_text(size=13))+
  labs(caption="Figure generated by author with data from Taniguchi 2019")
ggsave("Figure 8.2.tiff", units="in", width=8, height=4, dpi=300, compression = 'lzw')
